export { default as Cart } from './Cart/Cart'
export { default as Navbar } from './Navbar/Navbar'
export { default as Default } from './Default/Default'
export { default as ProductList } from './ProductList/ProductList'
export { default as ProductList2 } from './ProductList/ProductList2'
export { default as ProductAll } from './ProductList/ProductAll'
export { default as Details } from './Details/Details'
export { default as MainPage } from './MainPage/MainPage'